listen: 0.0.0.0:23333
key: xrayApi
xray:
    port: 23335

    protocol: vmess
    type: ws
    path: /localhost

    # protocol: vmess
    # type: tcp
    # tls: true
    # certificateFile: 
    # keyFile:

    # protocol: trojan
    # certificateFile: 
    # keyFile:

    # protocol: shadowsocks
    # method: aes-128-gcm # aes-128-gcm|aes-256-gcm|chacha20-ietf-poly1305
    # network: tcp,udp # tcp|udp|tcp,udp

    grpcPort: 10086
    
debug: false
