listen: 0.0.0.0:23333
key: xray-api
xray:
    port: 23335

    protocol: vmess
    type: ws
    path: /localhost

    # protocol: vmess
    # type: tcp
    # tls: true
    # certificateFile: 
    # keyFile:

    # protocol: trojan
    # certificateFile: 
    # keyFile:

    # protocol: shadowsocks
    # method: aes-128-gcm # aes-128-gcm|aes-256-gcm|chacha20-ietf-poly1305
    # network: tcp,udp # tcp|udp|tcp,udp

    grpcPort: 10086

    dns: ["223.5.5.5","119.29.29.29","8.8.8.8","1.1.1.1","https+local://cloudflare-dns.com/dns-query","localhost"]
    blockBT: true
    blockIps: ["0.0.0.0/8","10.0.0.0/8","100.64.0.0/10","127.0.0.0/8","169.254.0.0/16","172.16.0.0/12","192.0.0.0/24","192.0.2.0/24","192.168.0.0/16","198.18.0.0/15","198.51.100.0/24","203.0.113.0/24","::1/128","fc00::/7","fe80::/10"]
    blockDomains: ["epochtimes.com","epochtimes.com.tw","epochtimes.fr","epochtimes.de","epochtimes.jp","epochtimes.ru","epochtimes.co.il","epochtimes.co.kr","epochtimes-romania.com","domain:erabaru.net","domain:lagranepoca.com","domain:theepochtimes.com","domain:ntdtv.com","domain:ntd.tv","domain:ntdtv-dc.com","domain:ntdtv.com.tw","domain:minghui.org","renminbao.com","dafahao.com","dongtaiwang.com","falundafa.org","wujieliulan.com","ninecommentaries.com","shenyun.com"]
    
debug: false